In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
import pandas as pd

df = pd.read_csv("Daily Household Transactions.csv")

In [4]:
df.head

<bound method NDFrame.head of                      Date                   Mode        Category  \
0     20/09/2018 12:04:08                   Cash  Transportation
1     20/09/2018 12:03:15                   Cash            Food
2              19/09/2018  Saving Bank account 1    subscription
3     17/09/2018 23:41:17  Saving Bank account 1    subscription
4     16/09/2018 17:15:08                   Cash       Festivals
...                   ...                    ...             ...
2456             1/1/2015                   Cash  Transportation
2457             1/1/2015                   Cash  Transportation
2458             1/1/2015                   Cash  Transportation
2459             1/1/2015                   Cash            Food
2460             1/1/2015                   Cash  Transportation

                  Subcategory                                  Note  Amount  \
0                       Train                  2 Place 5 to Place 0    30.0
1                      snacks           Idli medu Vada mix 2 plates    60.0
2                     Netflix                  1 month subscription   199.0
3     Mobile Service Provider                     Data booster pack    19.0
4                Ganesh Pujan                           Ganesh idol   251.0
...                       ...                                   ...     ...
2456                      NaN      share jeep - Place T base to top    20.0
2457                      NaN  share auto - Place H to Place T base    20.0
2458                      NaN                  bus - brc to Place H    30.0
2459                      NaN                                   tea    10.0
2460                      NaN  share auto - hospital to brc station    10.0

     Income/Expense Currency
0           Expense      INR
1           Expense      INR
2           Expense      INR
3           Expense      INR
4           Expense      INR
...             ...      ...
2456        Expense      INR
2457        Expense      INR
2458        Expense      INR
2459        Expense      INR
2460        Expense      INR

[2461 rows x 8 columns]>

In [5]:
df.isnull().sum()

Date                0
Mode                0
Category            0
Subcategory       635
Note              521
Amount              0
Income/Expense      0
Currency            0
dtype: int64

In [6]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 9

In [7]:
df = df.drop_duplicates()

print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [8]:
df.info()

<class 'pandas.DataFrame'>
Index: 2452 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2452 non-null   str
 1   Mode            2452 non-null   str
 2   Category        2452 non-null   str
 3   Subcategory     1823 non-null   str
 4   Note            1940 non-null   str
 5   Amount          2452 non-null   float64
 6   Income/Expense  2452 non-null   str
 7   Currency        2452 non-null   str
dtypes: float64(1), str(7)
memory usage: 330.9 KB

In [9]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='%d/%m/%Y %H:%M:%S',
    errors='coerce'
)

In [10]:
print("Invalid dates:", df['Date'].isnull().sum())

Invalid dates: 1149

In [11]:
print(df['Date'].head(20).to_string())

0    2018-09-20 12:04:08
1    2018-09-20 12:03:15
2                    NaT
3    2018-09-17 23:41:17
4    2018-09-16 17:15:08
5    2018-09-15 06:34:17
6    2018-09-14 05:39:17
7    2018-09-13 21:35:15
8    2018-09-13 21:01:47
9    2018-09-13 21:01:32
10                   NaT
11                   NaT
12                   NaT
13                   NaT
14                   NaT
15                   NaT
16                   NaT
17                   NaT
18                   NaT
19                   NaT

In [12]:
print(df['Date'].tail(20).to_string())

2441   NaT
2442   NaT
2443   NaT
2444   NaT
2445   NaT
2446   NaT
2447   NaT
2448   NaT
2449   NaT
2450   NaT
2451   NaT
2452   NaT
2453   NaT
2454   NaT
2455   NaT
2456   NaT
2457   NaT
2458   NaT
2459   NaT
2460   NaT

In [13]:
df = pd.read_csv("Daily Household Transactions.csv")

In [14]:
df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

print("Invalid dates:", df['Date'].isnull().sum())

Invalid dates: 1158

In [15]:
df = pd.read_csv("Daily Household Transactions.csv")

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

print("Invalid dates:", df['Date'].isnull().sum())

Invalid dates: 1158

In [16]:
df = pd.read_csv("Daily Household Transactions.csv")

In [17]:
df['Date'] = pd.to_datetime(
    df['Date'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

print("Invalid dates:", df['Date'].isnull().sum())

Invalid dates: 0

In [18]:
df.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency
0,2018-09-20 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR
1,2018-09-20 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR
2,2018-09-19 00:00:00,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR
3,2018-09-17 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR
4,2018-09-16 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2461 entries, 0 to 2460
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            2461 non-null   datetime64[us]
 1   Mode            2461 non-null   str
 2   Category        2461 non-null   str
 3   Subcategory     1826 non-null   str
 4   Note            1940 non-null   str
 5   Amount          2461 non-null   float64
 6   Income/Expense  2461 non-null   str
 7   Currency        2461 non-null   str
dtypes: datetime64[us](1), float64(1), str(6)
memory usage: 277.7 KB

In [20]:
print("Income/Expense:")
print(df['Income/Expense'].value_counts())

print("\nCategories:")
print(df['Category'].value_counts())

print("\nPayment Modes:")
print(df['Mode'].value_counts())

print("\nCurrencies:")
print(df['Currency'].value_counts())

Income/Expense:
Income/Expense
Expense         2176
Transfer-Out     160
Income           125
Name: count, dtype: int64

Categories:
Category
Food                         907
Transportation               307
Household                    176
subscription                 143
Other                        126
Investment                   103
Health                        94
Family                        71
Apparel                       47
Recurring Deposit             47
Salary                        43
Money transfer                43
Gift                          30
Public Provident Fund         29
Equity Mutual Fund E          22
Beauty                        22
Gpay Reward                   21
Education                     18
Saving Bank account 1         17
maid                          17
Festivals                     16
Equity Mutual Fund A          14
Equity Mutual Fund F          13
Dividend earned on Shares     12
Interest                      12
Culture                       11
Small Cap fund 2              10
Small cap fund 1              10
Share Market                   8
Life Insurance                 7
Maturity amount                7
Petty cash                     6
Equity Mutual Fund C           6
Bonus                          6
Tourism                        5
Grooming                       4
Rent                           4
Cook                           4
Saving Bank account 2          3
water (jar /tanker)            3
Tax refund                     2
Self-development               2
Amazon pay cashback            2
scrap                          2
Documents                      2
Fixed Deposit                  2
garbage disposal               2
Social Life                    1
Equity Mutual Fund D           1
Equity Mutual Fund B           1
Name: count, dtype: int64

Payment Modes:
Mode
Saving Bank account 1    1223
Cash                     1046
Credit Card               162
Equity Mutual Fund B       11
Share Market Trading        5
Saving Bank account 2       5
Recurring Deposit           3
Debit Card                  2
Equity Mutual Fund C        1
Equity Mutual Fund A        1
Equity Mutual Fund D        1
Fixed Deposit               1
Name: count, dtype: int64

Currencies:
Currency
INR    2461
Name: count, dtype: int64

In [21]:
df['Year'] = df['Date'].dt.year
df['Month'] = df['Date'].dt.month
df['Month_Name'] = df['Date'].dt.strftime('%b')

In [22]:
df[['Date', 'Year', 'Month', 'Month_Name']].head()

                 Date  Year  Month Month_Name
0 2018-09-20 12:04:08  2018      9        Sep
1 2018-09-20 12:03:15  2018      9        Sep
2 2018-09-19 00:00:00  2018      9        Sep
3 2018-09-17 23:41:17  2018      9        Sep
4 2018-09-16 17:15:08  2018      9        Sep

In [23]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 2452

In [24]:
df.groupby('Income/Expense')['Amount'].agg(['count', 'sum'])

                count         sum
Income/Expense
Expense          2173  1955380.53
Income            125  3042397.35
Transfer-Out      154  1764780.90

In [25]:
total_income = df.loc[df['Income/Expense'] == 'Income', 'Amount'].sum()
total_expense = df.loc[df['Income/Expense'] == 'Expense', 'Amount'].sum()
net_savings = total_income - total_expense

print("Total Income:", total_income)
print("Total Expense:", total_expense)
print("Net Savings:", net_savings)

Total Income: 3042397.3499999996
Total Expense: 1955380.5300000003
Net Savings: 1087016.8199999994

In [26]:
monthly = df.groupby(['Year', 'Month', 'Month_Name', 'Income/Expense'])['Amount'].sum().reset_index()

monthly

     Year  Month Month_Name Income/Expense    Amount
0    2015      1        Jan        Expense  33870.00
1    2015      2        Feb        Expense  24308.00
2    2015      2        Feb         Income  49806.00
3    2015      3        Mar        Expense  32631.40
4    2015      3        Mar         Income  70806.00
..    ...    ...        ...            ...       ...
105  2018      8        Aug         Income  71735.75
106  2018      8        Aug   Transfer-Out  36543.00
107  2018      9        Sep        Expense   4724.00
108  2018      9        Sep         Income   3500.00
109  2018      9        Sep   Transfer-Out  25500.00

[110 rows x 5 columns]

In [27]:
monthly_summary = df.pivot_table(
    index=['Year', 'Month', 'Month_Name'],
    columns='Income/Expense',
    values='Amount',
    aggfunc='sum',
    fill_value=0
).reset_index()

monthly_summary['Savings'] = (
    monthly_summary.get('Income', 0) -
    monthly_summary.get('Expense', 0)
)

monthly_summary

Income/Expense,Year,Month,Month_Name,Expense,Income,Transfer-Out,Savings
0,2015,1,Jan,33870.00,0.00,0.00,-33870.00
1,2015,2,Feb,24308.00,49806.00,0.00,25498.00
2,2015,3,Mar,32631.40,70806.00,0.00,38174.60
3,2015,4,Apr,24222.00,49306.00,0.00,25084.00
4,2015,5,May,63118.00,47859.00,0.00,-15259.00
5,2015,6,Jun,19567.00,47859.00,0.00,28292.00
6,2015,7,Jul,31735.00,47859.00,0.00,16124.00
7,2015,8,Aug,43340.00,49806.00,0.00,6466.00
8,2015,9,Sep,18577.00,54606.00,0.00,36029.00
9,2015,10,Oct,32217.00,49806.00,0.00,17589.00
10,2015,11,Nov,26459.00,51306.00,0.00,24847.00
11,2015,12,Dec,72030.00,77335.00,0.00,5305.00
12,2016,1,Jan,38435.00,94806.00,0.00,56371.00
13,2016,2,Feb,27021.00,49806.00,0.00,22785.00
14,2016,3,Mar,16631.00,70806.00,0.00,54175.00
15,2016,4,Apr,28460.00,51562.45,0.00,23102.45
16,2016,5,May,38309.00,51556.00,0.00,13247.00
17,2016,6,Jun,32013.90,52284.00,0.00,20270.10
18,2016,7,Jul,36462.00,51556.00,0.00,15094.00
19,2016,8,Aug,46502.00,63894.00,0.00,17392.00
20,2016,9,Sep,29020.50,58893.00,0.00,29872.50
21,2016,10,Oct,31138.20,56647.00,0.00,25508.80
22,2016,11,Nov,69175.00,58096.00,0.00,-11079.00
23,2016,12,Dec,74916.60,56590.00,0.00,-18326.60
24,2017,1,Jan,117797.42,63101.00,15000.00,-54696.42
25,2017,2,Feb,43943.35,56021.00,26286.00,12077.65
26,2017,3,Mar,36502.08,56686.00,15000.00,20183.92
27,2017,4,Apr,23834.38,56957.00,15000.00,33122.62
28,2017,5,May,43830.10,56970.00,26043.00,13139.90
29,2017,6,Jun,32293.55,57827.00,216100.00,25533.45
30,2017,7,Jul,63873.00,181617.00,265100.00,117744.00
31,2017,8,Aug,101393.70,123383.00,26043.00,21989.30
32,2017,9,Sep,32419.00,62373.00,15000.00,29954.00
33,2017,10,Oct,45532.09,6000.00,175000.00,-39532.09
34,2017,11,Nov,64364.00,143155.00,28120.33,78791.00
35,2017,12,Dec,46805.00,82321.00,547108.96,35516.00
36,2018,1,Jan,142080.90,292938.00,94097.14,150857.10
37,2018,2,Feb,26218.00,64738.00,91704.00,38520.00
38,2018,3,Mar,23396.75,69343.50,23042.88,45946.75
39,2018,4,Apr,48339.58,65824.15,25500.00,17484.57
40,2018,5,May,40670.00,69238.00,36543.00,28568.00
41,2018,6,Jun,38161.02,68551.00,36549.59,30389.98
42,2018,7,Jul,67738.36,77267.50,25500.00,9529.14
43,2018,8,Aug,21305.65,71735.75,36543.00,50430.10
44,2018,9,Sep,4724.00,3500.00,25500.00,-1224.00

In [28]:
category_expense = df[df['Income/Expense'] == 'Expense'].groupby('Category')['Amount'].sum().sort_values(ascending=False)

category_expense

Category
Money transfer           606528.90
Investment               269858.00
Transportation           169053.78
Household                161645.58
subscription             114587.91
Food                      96393.10
Public Provident Fund     90000.00
Other                     87025.28
Family                    78582.20
Health                    66252.75
Tourism                   63608.85
Gift                      40168.00
Apparel                   25373.82
Recurring Deposit         22000.00
maid                      21839.00
Cook                      12443.00
Rent                      10709.00
Festivals                  6911.00
Culture                    4304.36
Beauty                     4189.00
Self-development           2357.00
Education                   537.00
Grooming                    400.00
Social Life                 298.00
water (jar /tanker)         148.00
Documents                   100.00
garbage disposal             67.00
Name: Amount, dtype: float64

In [29]:
normal_expenses = df[
    (df['Income/Expense'] == 'Expense') &
    (~df['Category'].isin([
        'Money transfer',
        'Investment',
        'Public Provident Fund',
        'Recurring Deposit'
    ]))
]

normal_category_expense = (
    normal_expenses.groupby('Category')['Amount']
    .sum()
    .sort_values(ascending=False)
)

normal_category_expense

Category
Transportation         169053.78
Household              161645.58
subscription           114587.91
Food                    96393.10
Other                   87025.28
Family                  78582.20
Health                  66252.75
Tourism                 63608.85
Gift                    40168.00
Apparel                 25373.82
maid                    21839.00
Cook                    12443.00
Rent                    10709.00
Festivals                6911.00
Culture                  4304.36
Beauty                   4189.00
Self-development         2357.00
Education                 537.00
Grooming                  400.00
Social Life               298.00
water (jar /tanker)       148.00
Documents                 100.00
garbage disposal           67.00
Name: Amount, dtype: float64

In [30]:
# Fill missing values
df['Subcategory'] = df['Subcategory'].fillna('Unknown')
df['Note'] = df['Note'].fillna('No Note')

# Remove extra spaces from text columns
df['Mode'] = df['Mode'].str.strip()
df['Category'] = df['Category'].str.strip()
df['Income/Expense'] = df['Income/Expense'].str.strip()
df['Currency'] = df['Currency'].str.strip()

print("Missing values after cleaning:")
print(df.isnull().sum())

Missing values after cleaning:
Date              0
Mode              0
Category          0
Subcategory       0
Note              0
Amount            0
Income/Expense    0
Currency          0
Year              0
Month             0
Month_Name        0
dtype: int64

In [31]:
# Create separate amount columns for easier Power BI analysis

df['Expense_Amount'] = df['Amount'].where(
    df['Income/Expense'] == 'Expense', 0
)

df['Income_Amount'] = df['Amount'].where(
    df['Income/Expense'] == 'Income', 0
)

df['Transfer_Amount'] = df['Amount'].where(
    df['Income/Expense'] == 'Transfer-Out', 0
)

# Create Month-Year field
df['Month_Year'] = df['Date'].dt.to_period('M').astype(str)

# Create a proper date field for monthly sorting
df['Month_Year_Date'] = df['Date'].dt.to_period('M').dt.to_timestamp()

df.head()

,Date,Mode,Category,Subcategory,Note,Amount,Income/Expense,Currency,Year,Month,Month_Name,Expense_Amount,Income_Amount,Transfer_Amount,Month_Year,Month_Year_Date
0,2018-09-20 12:04:08,Cash,Transportation,Train,2 Place 5 to Place 0,30.0,Expense,INR,2018,9,Sep,30.0,0.0,0.0,2018-09,2018-09-01
1,2018-09-20 12:03:15,Cash,Food,snacks,Idli medu Vada mix 2 plates,60.0,Expense,INR,2018,9,Sep,60.0,0.0,0.0,2018-09,2018-09-01
2,2018-09-19 00:00:00,Saving Bank account 1,subscription,Netflix,1 month subscription,199.0,Expense,INR,2018,9,Sep,199.0,0.0,0.0,2018-09,2018-09-01
3,2018-09-17 23:41:17,Saving Bank account 1,subscription,Mobile Service Provider,Data booster pack,19.0,Expense,INR,2018,9,Sep,19.0,0.0,0.0,2018-09,2018-09-01
4,2018-09-16 17:15:08,Cash,Festivals,Ganesh Pujan,Ganesh idol,251.0,Expense,INR,2018,9,Sep,251.0,0.0,0.0,2018-09,2018-09-01

In [32]:
# Define essential and discretionary expense categories

essential_categories = ['Transportation', 'Household', 'Food', 'Family', 'Health', 'maid', 'Cook', 'Rent', 'water (jar /tanker)', 'Documents', 'garbage disposal', 'Education', 'Self-development']

discretionary_categories = ['subscription', 'Tourism', 'Gift', 'Apparel', 'Festivals', 'Culture', 'Beauty', 'Grooming', 'Social Life']

# Create spending type
df['Spending_Type'] = 'Other'

df.loc[(df['Income/Expense'] == 'Expense') & (df['Category'].isin(essential_categories)), 'Spending_Type'] = 'Essential'
df.loc[(df['Income/Expense'] == 'Expense') & (df['Category'].isin(discretionary_categories)), 'Spending_Type'] = 'Discretionary'

df[['Category', 'Spending_Type']].drop_duplicates().sort_values('Category')

                       Category  Spending_Type
270         Amazon pay cashback          Other
21                      Apparel  Discretionary
84                       Beauty  Discretionary
1739                      Bonus          Other
2196                       Cook      Essential
116                     Culture  Discretionary
40    Dividend earned on Shares          Other
472                   Documents      Essential
279                   Education      Essential
634        Equity Mutual Fund A          Other
1171       Equity Mutual Fund B          Other
700        Equity Mutual Fund C          Other
901        Equity Mutual Fund D          Other
19         Equity Mutual Fund E          Other
732        Equity Mutual Fund F          Other
17                       Family      Essential
4                     Festivals  Discretionary
687               Fixed Deposit          Other
1                          Food      Essential
31                         Gift  Discretionary
556                 Gpay Reward          Other
1828                   Grooming  Discretionary
87                       Health      Essential
36                    Household      Essential
46                     Interest          Other
1751                 Investment          Other
57               Life Insurance          Other
653             Maturity amount          Other
102              Money transfer          Other
8                         Other          Other
460                  Petty cash          Other
28        Public Provident Fund          Other
767           Recurring Deposit          Other
2172                       Rent      Essential
33                       Salary          Other
29        Saving Bank account 1          Other
773       Saving Bank account 2          Other
244            Self-development      Essential
238                Share Market          Other
10             Small Cap fund 2          Other
11             Small cap fund 1          Other
614                 Social Life  Discretionary
121                  Tax refund          Other
204                     Tourism  Discretionary
0                Transportation      Essential
2253           garbage disposal      Essential
103                        maid      Essential
280                       scrap          Other
2                  subscription  Discretionary
2259        water (jar /tanker)      Essential

In [33]:
# Detect unusually high regular expenses using IQR

expense_mask = (df['Income/Expense'] == 'Expense') & (~df['Category'].isin(['Money transfer', 'Investment', 'Public Provident Fund', 'Recurring Deposit']))

Q1 = df.loc[expense_mask, 'Amount'].quantile(0.25)
Q3 = df.loc[expense_mask, 'Amount'].quantile(0.75)
IQR = Q3 - Q1
upper_limit = Q3 + (1.5 * IQR)

df['Unusual_Expense'] = 'No'
df.loc[expense_mask & (df['Amount'] > upper_limit), 'Unusual_Expense'] = 'Yes'

print("Q1:", Q1)
print("Q3:", Q3)
print("Upper Limit:", upper_limit)
print("Unusual Expenses:", (df['Unusual_Expense'] == 'Yes').sum())

Q1: 30.0
Q3: 251.0
Upper Limit: 582.5
Unusual Expenses: 265

In [34]:
unusual_expenses = df[df['Unusual_Expense'] == 'Yes'][['Date', 'Category', 'Subcategory', 'Note', 'Amount', 'Spending_Type']]
unusual_expenses.sort_values('Amount', ascending=False)

,Date,Category,Subcategory,Note,Amount,Spending_Type
608,2018-01-18 21:57:46,Transportation,Bike,Two Wheeler Bikedelux second installment,50000.0,Essential
582,2018-01-27 18:15:53,Transportation,Bike,Two Wheeler Bikedelux third installment,43000.0,Essential
1080,2017-08-08 00:00:00,Tourism,Trip,Tours and Travel,43000.0,Discretionary
706,2017-12-20 10:31:16,subscription,Edtech Course,Renewal,28400.0,Discretionary
771,2017-11-30 20:20:53,Health,Health,Family's Glasses,22700.0,Essential
...,...,...,...,...,...,...
1416,2017-05-01 00:00:00,Apparel,Clothing,H&M Tshirt for Family,599.0,Discretionary
670,2018-01-01 00:00:00,Household,gadgets,Logitech mouse,599.0,Essential
1889,2016-09-06 00:00:00,Transportation,Travels,Place 6 to Place 2,598.5,Essential
76,2018-08-13 18:33:36,Household,Kirana,Supermart,594.0,Essential
1233,2017-06-23 09:52:10,Other,Unknown,Credit Card fee,590.0,Other

In [35]:
print("Unusual expense count by category:")
print(df[df['Unusual_Expense'] == 'Yes']['Category'].value_counts())

print("\nTotal amount of unusual expenses: ₹", round(df.loc[df['Unusual_Expense'] == 'Yes', 'Amount'].sum(), 2))

Unusual expense count by category:
Category
Household           49
Transportation      40
Family              30
subscription        27
Other               26
Food                21
Health              18
Gift                15
maid                12
Apparel             10
Rent                 4
Cook                 4
Festivals            3
Self-development     2
Tourism              2
Culture              1
Beauty               1
Name: count, dtype: int64

Total amount of unusual expenses: ₹ 774835.67

In [36]:
unusual_summary = df[df['Unusual_Expense'] == 'Yes'].groupby('Category')['Amount'].agg(['count', 'sum']).sort_values('sum', ascending=False)

unusual_summary

                  count        sum
Category
Transportation       40  152881.98
Household            49  141813.58
subscription         27   89231.91
Other                26   74032.00
Family               30   68709.20
Tourism               2   63000.00
Health               18   55243.00
Gift                 15   35414.00
Food                 21   23368.00
maid                 12   19840.00
Apparel              10   19234.00
Cook                  4   12443.00
Rent                  4   10709.00
Festivals             3    3799.00
Self-development      2    2357.00
Beauty                1    2000.00
Culture               1     760.00

In [37]:
print("Final dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())
print("\nData types:")
print(df.dtypes)

Final dataset shape: (2452, 18)

Missing values:
Date               0
Mode               0
Category           0
Subcategory        0
Note               0
Amount             0
Income/Expense     0
Currency           0
Year               0
Month              0
Month_Name         0
Expense_Amount     0
Income_Amount      0
Transfer_Amount    0
Month_Year         0
Month_Year_Date    0
Spending_Type      0
Unusual_Expense    0
dtype: int64

Duplicate rows: 0

Data types:
Date               datetime64[us]
Mode                          str
Category                      str
Subcategory                   str
Note                          str
Amount                    float64
Income/Expense                str
Currency                      str
Year                        int32
Month                       int32
Month_Name                    str
Expense_Amount            float64
Income_Amount             float64
Transfer_Amount           float64
Month_Year                    str
Month_Year_Date    datetime64[us]
Spending_Type                 str
Unusual_Expense               str
dtype: object

In [38]:
df[['Date', 'Category', 'Amount', 'Income/Expense', 'Expense_Amount', 'Income_Amount', 'Transfer_Amount', 'Month_Year', 'Spending_Type', 'Unusual_Expense']].head()

,Date,Category,Amount,Income/Expense,Expense_Amount,Income_Amount,Transfer_Amount,Month_Year,Spending_Type,Unusual_Expense
0,2018-09-20 12:04:08,Transportation,30.0,Expense,30.0,0.0,0.0,2018-09,Essential,No
1,2018-09-20 12:03:15,Food,60.0,Expense,60.0,0.0,0.0,2018-09,Essential,No
2,2018-09-19 00:00:00,subscription,199.0,Expense,199.0,0.0,0.0,2018-09,Discretionary,No
3,2018-09-17 23:41:17,subscription,19.0,Expense,19.0,0.0,0.0,2018-09,Discretionary,No
4,2018-09-16 17:15:08,Festivals,251.0,Expense,251.0,0.0,0.0,2018-09,Discretionary,No

In [39]:
print("Final dataset shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Final dataset shape: (2452, 18)

Missing values:
Date               0
Mode               0
Category           0
Subcategory        0
Note               0
Amount             0
Income/Expense     0
Currency           0
Year               0
Month              0
Month_Name         0
Expense_Amount     0
Income_Amount      0
Transfer_Amount    0
Month_Year         0
Month_Year_Date    0
Spending_Type      0
Unusual_Expense    0
dtype: int64

Duplicate rows: 0

In [40]:
df.to_csv('Expense_Intelligence_Cleaned.csv', index=False)

print("Cleaned dataset exported successfully!")
print("Rows:", len(df))
print("Columns:", len(df.columns))

Cleaned dataset exported successfully!
Rows: 2452
Columns: 18

In [41]:
df.to_excel("Expense_Intelligence_Cleaned.xlsx", index=False)